// Mocks generated by Mockito 5.4.5 from annotations
// in flagship/test/emotion_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flagship/emotionAi/emotion_tools.dart' as _i2;
import 'package:flagship/model/account_settings.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScoreResult_0 extends _i1.SmartFake implements _i2.ScoreResult {
  _FakeScoreResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmotionAITools].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmotionAITools extends _i1.Mock implements _i2.EmotionAITools {
  MockEmotionAITools() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String createCpFiled(List<Map<String, dynamic>>? path) =>
      (super.noSuchMethod(
            Invocation.method(#createCpFiled, [path]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#createCpFiled, [path]),
            ),
          )
          as String);

  @override
  String createSpoFiled(List<Map<String, dynamic>>? path) =>
      (super.noSuchMethod(
            Invocation.method(#createSpoFiled, [path]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#createSpoFiled, [path]),
            ),
          )
          as String);

  @override
  _i4.Future<_i5.AccountSettings?> fetchRessources(String? envId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRessources, [envId]),
            returnValue: _i4.Future<_i5.AccountSettings?>.value(),
          )
          as _i4.Future<_i5.AccountSettings?>);

  @override
  _i4.Future<_i2.ScoreResult> fetchScore(String? visitorId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchScore, [visitorId]),
            returnValue: _i4.Future<_i2.ScoreResult>.value(
              _FakeScoreResult_0(
                this,
                Invocation.method(#fetchScore, [visitorId]),
              ),
            ),
          )
          as _i4.Future<_i2.ScoreResult>);
}
